EXP_NAME: BERT-tfidf_title_category_select
SEED: 223
MODE:
  do_train: true
  do_test: false
DATASET:
  name: BERT
  data_path: ../data/Part1
  saved_data_path: ../data-direct/tfidf_title_category_select/BERT_w512
  PARAMETERS:
    max_word_len: 512
  direct_path: ../data-direct/tfidf_title_category_select
TOKENIZER:
  name: bert
MODEL:
  modelname: bert
  PARAMETERS:
    pretrained_name: skt/kobert-base-v1
    num_classes: 2
  CHECKPOINT:
    checkpoint_path: null
TRAIN:
  batch_size: 8
  num_training_steps: 10000
  accumulation_steps: 1
  num_workers: 12
  use_wandb: true
LOG:
  log_interval: 1
  eval_interval: 1000
OPTIMIZER:
  lr: 1.0e-05
  weight_decay: 0.0005
SCHEDULER:
  warmup_ratio: 0.1
  use_scheduler: true
RESULT:
  savedir: ./saved_model-direct/tfidf_title_category_select
