EXP_NAME: HAND-tfidf_title_category_select
SEED: 223
DATASET:
  name: HAND
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_sent_len: 16
    max_word_len: 64
  direct_path: ../data-direct/tfidf_title_category_select
TOKENIZER:
  name: mecab
  vocab_path: ./word-embeddings/glove/glove.txt
  max_vocab_size: 50000
TRAIN:
  batch_size: 256
  num_workers: 12
RESULT:
  savedir: ../data-direct/tfidf_title_category_select
  dataname: HAND_s16_w64
