EXP_NAME: BERT-tfidf_content_category_select
SEED: 223
DATASET:
  name: BERT
  data_path: ../data/Part1
  saved_data_path: false
  PARAMETERS:
    max_word_len: 512
  direct_path: ../data-direct/tfidf_content_category_select
TOKENIZER:
  name: bert
TRAIN:
  batch_size: 256
  num_workers: 12
RESULT:
  savedir: ../data-direct/tfidf_content_category_select
  dataname: BERT_w512
