EXP_NAME: BERT
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: BERT
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/BERT_w512
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert
    
MODEL:
    modelname: bert
    PARAMETERS:
        pretrained_name: 'skt/kobert-base-v1'
        num_classes: 2
    CHECKPOINT:
        checkpoint_path: null

TRAIN:
    batch_size: 8
    num_training_steps: 10000
    accumulation_steps: 1
    num_workers: 12
    use_wandb: True

LOG:
    log_interval: 1
    eval_interval: 1000

OPTIMIZER:
    lr: 0.00001
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: '/saved_model/Part1'
