EXP_NAME: KoBERTSeg
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: KoBERTSeg
    data_path: ../data/Part2
    PARAMETERS:
        max_word_len: 512
        window_size: 3

MODEL:
    modelname: kobertseg
    PARAMETERS:
        window_size: 3
        finetune_bert: True
    CHECKPOINT:
        checkpoint_path: null

TRAIN:
    batch_size: 8
    num_training_steps: 15000
    accumulation_steps: 1
    num_workers: 12
    use_wandb: True

LOG:
    log_interval: 1
    eval_interval: 2500

OPTIMIZER:
    lr: 0.00001
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: '/saved_model/Part2'
