EXP_NAME: FNDNet
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: FNDNet
    data_path: ../data/Part1 # news article directory
    saved_data_path: ../data/Part1/FNDNet_w1000
    PARAMETERS:
        max_word_len: 1000

TOKENIZER: 
    name: mecab
    vocab_path: /word-embeddings/glove/glove.txt
    max_vocab_size: 50000  
    
MODEL:
    modelname: fndnet
    freeze_word_embed: True
    use_pretrained_word_embed: True
    PARAMETERS:
        num_classes: 2
        vocab_len: 50002
        dims: 128
        embed_dims: 100
        dropout: 0.2
    CHECKPOINT:
        checkpoint_path: null

TRAIN:
    batch_size: 256
    num_training_steps: 100000
    accumulation_steps: 1
    num_workers: 12
    use_wandb: True

LOG:
    log_interval: 10
    eval_interval: 1000

OPTIMIZER:
    lr: 0.00003
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: '/saved_model/Part1'
